apiVersion: v1
kind: Service
metadata:
  name: openexecutive-api
  labels:
    app.kubernetes.io/name: openexecutive-api
    app.kubernetes.io/part-of: openexecutive
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openexecutive-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: openexecutive-ui
  labels:
    app.kubernetes.io/name: openexecutive-ui
    app.kubernetes.io/part-of: openexecutive
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openexecutive-ui
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: openexecutive-honcho
  labels:
    app.kubernetes.io/name: openexecutive-honcho
    app.kubernetes.io/part-of: openexecutive
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openexecutive-honcho
  ports:
    - name: http
      port: 8000
      targetPort: http
